package com.donglaistd.jinli.database.entity.backoffice;

public enum BackOfficeRole {
    ADMIN, //超级管理员权限
    PLATFORM, //T平台API权限
    LOTTERY, //开奖权限
    LOGIN,  //登录到后台权限
    USEROPT,  // 用户操作权限
    PLATFORM_Q,  // Q平台API权限

    //一级
    INDEX,//首页
    USER, //用户管理权限
    REVENUEANALYSIS, //收入分析权限
    LIVEUSER, //主播管理权限
    JINLI,//锦鲤直播

    BACKOFFICEMESSAGE, //系统管理权限
    GIFT,//礼物权限
    GUESS,//官方游戏权限
    BACKOFFICE_T,//T平台管理权限
    BACKOFFICE_Q,//Q平台管理权限

    //二级
    USERLIST,//用户列表权限
    BANUSERLIST,//封禁用户列表
    NEWUSERCHART,//新增用户
    ACTIVEUSERCHART,//活跃用户
    RETAINEDUSERCHART,//用户留存
    CONVERSIONRATESCHART,//付费转换
    MOBILEDEVICESCHART,//相关设备
    COINOPERATIONRECORD,//金币修改记录列表

    REVENUEINDEX,//收入分析
    GIFTCONSUMPTIONLIST,//礼物消费记录
    LIVEUSERRECEIVEDGIFTLIST,//主播收礼记录
    BETSRECORDLIST,//投注记录
    REVENUEDATA,//收入记录
    PAYMENTPENETRATION,//付费渗透
    NEWPLAYERVALUE,//新玩家价值
    PAYMENTHABIT,//付费习惯

    LIVEUSERROOM,//直播监控
    LIVEUSERLIST,//主播列表
    BANLIVEUSERLIST,//封禁主播列表
    LIVEUSEREXAMINE,//主播审核
    APPROVEDLIVEUSER,//审核记录

    LIVEUSERRECORD,//直播记录
    LIVEUSERATTENDANCE,//直播考勤
    LIVESOURCELINE,//CDN管理
    REPORTLIST,//举报列表
    PERSONDIARYAPPROVED,//动态列表
    PERSONDIARYLIST,//动态审核
    PERSONDIARYREJECT,//动态驳回

    LIVEUSERLISTJINLI,//锦鲤直播列表
    SENDBACKOFFICEMESSAGE,//走马灯消息
    MESSAGESETTINGS,//直播公告
    SENDBACKOFFICEMESSAGERECORD,//走马灯消息操作记录
    MESSAGESETTINGSRECORD,//直播公告操作记录
    FEEDBACK,//反馈信息

    CAROUSEL,//轮播图
    MATCHCAROUSEL,//赛事轮播图
    LIVECAROUSEL,//直播轮播图
    GUESSCAROUSEL,//竞猜轮播图
    GIFTLIST,//礼物列表

    //T平台
    INDEXT,
    LIVEROOMLISTT,//直播监控
    LIVEUSERLISTT,//主播列表
    BANLIVEUSERLISTT,//封禁主播列表
    LIVEUSERAPPLYT,//主播审核
    USERLISTT,//用户列表

    LIVEUSERRECORDT,//直播记录

    GIFTCONSUMPTIONLISTT,//礼物记录

    RECHARGERECORDT,//充值记录

    GIFTLISTT,//礼物管理
    MESSAGESETTINGST,//消息管理
    DOMAINNAMESETT,//域名设置
    DOMAINNAMESETRECORDT,//域名操作记录
    GUESSLIST,//竞猜列表
    GUESSSTATISTICS,//已开奖统计
    OFFICIALLIVELIST,//当前官方直播间
    OFFICIALLIVERECORDS,//历史官方直播间列表
    GUESSLISTBOX,//竞猜列表容器
    GUESSNOTSTART,//尚未开始
    GUESSWAITPRIZE,//尚未开奖
    GUESSSHOWOVER,//已开奖
    GUESSADD,//新增竞猜
    GUESSEDIT,//编辑竞猜
    OFFICIALLIVEADD,//新增官方直播间
    OFFICIALLIVECOLSE,//关闭官方直播间
    //Q平台
    INDEXQ,
    LIVEROOMLISTQ,//直播监控
    LIVEUSERLISTQ,//主播列表
    BANLIVEUSERLISTQ,//封禁主播列表
    LIVEUSERAPPLYQ,//主播审核
    USERLISTQ,//用户列表

    LIVEUSERRECORDQ,//直播记录

    GIFTCONSUMPTIONLISTQ,//礼物记录

    RECHARGERECORDQ,//充值记录
    GIFTLISTQ,//礼物管理
    MESSAGESETTINGSQ,//消息管理
    DOMAINNAMESETQ,//域名设置
    DOMAINNAMESETRECORDQ,//域名操作记录



    //三级
    SEARCHUSERID,//搜索用户ID
    USERDETAILS,//用户详情
    USERBETRECORD,//投注记录
    BANUSERUSERDETAILS,//封禁用户用户详情
    BANUSERUSERBETRECORD,//封禁用户投注记录

    CLOSELIVE,//关闭直播间
    SEARCHROOMUSERID,//直播监控搜索用户ID
    LIVEUSERDETAILINFO,//主播详情
    SEARCHLIVEUSERID,//搜索主播ID

    SEARCHBANLIVEUSERID,//封禁主播列表 搜索主播ID
    UNLOCKLIVELIST,//解封主播

    LIVEUSERRECORDSEARCHLIVEUSERID,//搜索主播ID
    LIVEUSERRECORDEXCEL,//导出excel
    LIVEUSERRECORDLIVEUSERDETAILINFO,//直播记录主播详情

    OPENORCLOSELIVESOURCELINE,//开关CDN

    LIVEUSERJINLIDETAILINFO,//锦鲤主播详情
    OPENORCLOSEGIFT,//开关礼物
    CHANGEPRICE,//编辑礼物


    CLOSTLIVET,//关闭直播间T
    SEARCHUSERIDLIVEROOMLISTT,//搜索用户id

    SEARCHLIVEUSERIDLIVEUSERLISTT,//搜索主播ID

    RECEIVEDGIFTLISTT,

    //四级
    OPERATIONUSERCOIN,//操作用户金币权限
    BANUSER,//拉黑用户权限
    BECOMELIVEUSER,//成为主播
    CHANGEPASSWORD,//修改用户密码
    UNSEALEDUSER,//解封用户

    LIVEUSER_LIVEUSERROLE,//主播权限

    BANLIVEUSER,//封禁主播
    LIVEUSERDETAILINFOCHANGEPASSWORD,
    BANUSERLISTUSERDETAILS,
    BANUSERLISTOPERATIONUSERCOIN,
    BANUSERLISTBANUSER,
    BANUSERLISTBECOMELIVEUSER,
    BANUSERLISTCHANGEPASSWORD,


    LIVEUSERRECORD_LIVEUSERROLE,
    LIVEUSERRECORDBANLIVEUSER,
    LIVEUSERRECORDLIVEUSERDETAILINFOCHANGEPASSWORD,

    JINLI_LIVEUSERROLE,
    JINLIBANLIVEUSER,
    JINLILIVEUSERDETAILINFOCHANGEPASSWORD,

    LIVEUSERDETAILINFOT_LIVEUSERROLE,
    LIVEUSERDETAILINFOTBANLIVEUSER,//
    LIVEUSERDETAILINFOTCANGEPASSWORD,
    BANLIVEUSERLISTTUNLOCKLIVELIST,
    ALLBANLIVEUSERLISTTUNLOCKLIVELIST,
    LIVEUSERAPPLYTBOX,
    LIVEUSERAUDITRECORDST,
    LIVEUSERRECORDT_LIVEUSERROLE,
    LIVEUSERDETAILINFOQ_LIVEUSERROLE,
    LIVEUSERDETAILINFOT,
    LIVEUSERDETAILINFOQ,//主播详情
    LIVEUSERRECORDQ_LIVEUSERROLE,

    LIVEUSERRECORDTSEARCHLIVEUSERID,
    LIVEUSERRECORDTEXCEL,
    LIVEUSERRECORDTDETAILINFOT,
    LIVEUSERRECORDT_GIFT,
    LIVEUSERRECORDT_PUBLICCHAT,
    LIVEUSERRECORDTBANLIVEUSER,
    LIVEUSERRECORDTCANGEPASSWORD,

    GIFTLISTTOPENORCLOSEGIFT,
    GIFTLISTTCHANGEPRICE,
    MESSAGESETTINGSTBOX,
    BACKOFFICEMESSAGET,
    MESSAGESETTINGSRECORDT,
    BACKOFFICEMESSAGERECORDT,
    UPDATEDOMAINNAMET,
    TESTDOMAINNAMET,
    REMOVEDOMAINT,
    CLOSTLIVEQ,
    SEARCHUSERIDLIVEROOMLISTQ,
    LIVEUSERDETAILINFOQ_GIFT,
    LIVEUSERDETAILINFOQ_PUBLICCHAT,
    LIVEUSERDETAILINFOQBANLIVEUSER,
    LIVEUSERDETAILINFOQCANGEPASSWORD,
    SEARCHLIVEUSERIDLIVEUSERLISTQ,
    BANLIVEUSERLISTTUNLOCKLIVELISQ,
    ALLBANLIVEUSERLISTTUNLOCKLIVELISQ,
    LIVEUSERAPPLYQBOX,
    LIVEUSERAUDITRECORDSQ,
    LIVEUSERRECORDQ_GIFT,
    LIVEUSERRECORDQ_PUBLICCHAT,
    LIVEUSERRECORDQBANLIVEUSER,
    LIVEUSERRECORDQCANGEPASSWORD,
    LIVEUSERRECORDQDETAILINFOQ,
    LIVEUSERRECORDQEXCEL,
    LIVEUSERRECORDQSEARCHLIVEUSERID,
    GIFTCONSUMPTIONLISTQBOX,
    RECEIVEDGIFTLISTQ,
    GIFTLISTQOPENORCLOSEGIFT,
    GIFTLISTQCHANGEPRICE,
    MESSAGESETTINGSQBOX,
    BACKOFFICEMESSAGEQ,
    MESSAGESETTINGSRECORDQ,
    BACKOFFICEMESSAGERECORDQ,
    UPDATEDOMAINNAMEQ,
    TESTDOMAINNAMEQ,
    REMOVEDOMAINQ,

    GIFTCONSUMPTIONT,
    BACKOFFICE,
    ADDNEWBACKOFFICE,
    EDITROLE,
    CHANGEBACKOFFICEPASSWORD,
    BACKOFFICEMANAGEMENT,
    BANBACKOFFICE,
    BACKOIFFICEROLE,
    THESERVER,
    OPENCLOSESERVER,
    CHANGEPASSWORDRECORD,
    INDEXJINLI,
    UPDATELIVEUSERSHAREDPLATFORM,
    JINLIUPDATELIVEUSERSHAREDPLATFORM,
    TUPDATELIVEUSERSHAREDPLATFORM,
    QUPDATELIVEUSERSHAREDPLATFORM
}
